name = "maile-portal"
main = "src/index.js"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

[vars]
DOMAIN = "freedomaint.com"
APP_BASE_URL = "https://portal.freedomaint.com"
DEFAULT_ALIAS_LIMIT = "3"
SESSION_TTL_SECONDS = "1209600"
RESET_TTL_SECONDS = "3600"

[[d1_databases]]
binding = "DB"
database_name = "mail-portal"
database_id = "b336c190-139a-4c72-b2f4-8a586021e763"
